version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 20
    commands:
      - echo "Installing NPM dependencies..."
      - npm install
  pre_build:
    commands:
      - echo "Running pre-build steps..."
      # Optional: run lint or tests
      # - npm test
  build:
    commands:
      - echo "Build phase..."
      # If you have a build step like TypeScript compilation
      - npm run build || echo "No build step defined, continuing..."
  post_build:
    commands:
      - echo "Build finished. Ready for Elastic Beanstalk deployment."

artifacts:
  files:
    - '**/*'
  discard-paths: no
